#define CONFIG_BUILD_DEBUG 1
#define CONFIG_TRACE_LEVEL 4
#define CONFIG_DEBUG_IDT_GDT 1
#define CONFIG_DEBUG_TSS 1
#define CONFIG_DEBUG_MEMORY 1
#define CONFIG_DEBUG_PAGING 1
#define CONFIG_DEBUG_STACK_HEAP 1
#define CONFIG_DEBUG_PROCESS_MGMT 1
